BSDS 5005 Lab
Lecture 3 - 9/26/18 

```{r}
library(ggplot2)
#1. Write R code using ggplot2 to recreate the density plot with area under the curve
x <- seq(-4,4,by=0.1)
y <- dnorm(x)
pdf_f <- data.frame(x,y)
pdf_p <- ggplot(data=pdf_f, aes(x=x,y=y)) +
  geom_line()+
  theme_classic()+
  geom_ribbon(data=pdf_f[pdf_f$x < -1,], aes(x,ymax=y,ymin=0),fill="red",color="black",alpha=1) +
  labs(y="Density", title="Pr(x <= -1)") +
  theme_classic()
pdf_p
```

```{r}
#2.
library(gapminder)
data("gapminder")
gapminder_2007 <- subset(gapminder, year==2007)

gapminder_plot <- ggplot() + 
  geom_point(data=gapminder_2007,aes(x=gdpPercap, y=lifeExp)) +
  annotate("text", x=gapminder_2007[(gapminder_2007$continent=="Europe" & gapminder_2007$gdpPercap>40000),]$gdpPercap, y=gapminder_2007[(gapminder_2007$continent=="Europe" & gapminder_2007$gdpPercap>40000),]$lifeExp, label=c("Ireland","Norway"),color="blue",size=3) +
  labs(x="GDP per Capita",y="Life expectancy")
gapminder_plot
```

```{r}
gapminder_plot_1 <- ggplot() + 
  geom_point(shape=21,color="black",fill="white",stroke=1.5,data=gapminder_2007,aes(x=gdpPercap, y=lifeExp)) +
  labs(x="GDP per Capita",y="Life expectancy") +
  geom_rect(aes(xmin=39000,xmax=51000,ymin=75,ymax=85),fill="red", alpha=0.25) +
  annotate("text",label="Countries with \nhighest GDP", x=45000,y=72.5)
gapminder_plot_1

```


